<section id="sectionRegistroVisualizar" class="jumbotron jumbotron-fluid d-flex justify-content-center"
         xmlns="http://www.w3.org/1999/html">

    <div id="divFundoDados" class="row">
        <div id="tituloVisualizar" class="container-fluid">
            <h1>
                Visualizar
                <small>Dashboard</small>
            </h1>
        </div>
        <div id="cardDadosUsuario" class="col-12">
            <div class="row">
                <div class="col-3">

                    <div class="row">

                        <div class="col-4 text-white bg-danger text-center">
                            <i class="fa fa-unlock-alt"></i>
                        </div>

                        <div class="col-8 bg-light">
                            <h3 class="card-title font-weight-bold"><?= isset($UserQTD[0])?$UserQTD[0]:0 ?></h3>
                            <p class="card-text">Demandas do Usuário Abertas</p>
                        </div>

                    </div>

                </div>

                <div class="col-3">

                    <div class="row">

                        <div class="col-4 text-white bg-success text-center">
                            <i class="fa fa-lock"></i>
                        </div>

                        <div class="col-8 bg-light">
                            <h3 class="card-title font-weight-bold"><?= isset($UserQTD[1])?$UserQTD[1]:0 ?></h3>
                            <p class="card-text">Demandas do Usuário Fechadas</p>
                        </div>

                    </div>

                </div>

                <div class="col-3">

                    <div class="row">

                        <div class="col-4 text-white bg-primary text-center">
                            <i class="fa fa-user-plus"></i>
                        </div>

                        <div class="col-8 bg-light">
                            <h3 class="card-title font-weight-bold"><?= isset($UserQTD[2])?$UserQTD[2]:0 ?></h3>
                            <p class="card-text">Total Demandas do Usuário</p>
                        </div>

                    </div>

                </div>

                <div class="col-3">

                    <div class="row">

                        <div class="col-4 text-white bg-warning text-center">
                            <i class="fa fa-database"></i>
                        </div>

                        <div class="col-8 bg-light">
                            <h3 class="card-title font-weight-bold"><?= isset($UserQTD[3])?$UserQTD[3]:0 ?></h3>
                            <p class="card-text">Base de dados total</p>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div id="cardTable" class="card text-center col-6">
            <div class="card-header">
                <p class="font-weight-bold"><i class="fa fa-file-excel-o" aria-hidden="true"></i> TABELA</p>
            </div>
            <div class="card-body">
                <div id="divFiltroDados" class="btn-group">
                    <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-filter" aria-hidden="true"></i> Filtro</button>

                    <div class="dropdown-menu">
                        <a id="filtroDemandaAberta" class="dropdown-item" href="#"><i class="fa fa-unlock-alt"></i> Demandas do Usuário Abertas</a>
                        <a id="filtroDemandaFechada" class="dropdown-item" href="#"><i class="fa fa-lock"></i> Demandas do Usuário Fechadas</a>
                        <a id="filtroDemandaTotal" class="dropdown-item" href="#"><i class="fa fa-user-plus"></i> Total Demandas do Usuário</a>
                        <div class="dropdown-divider"></div>
                        <a id="filtroBaseTotal" class="dropdown-item" href="#"><i class="fa fa-database"></i> Base de dados total</a>
                    </div>
                </div>
                <table id="tableDemanda" class="table table-striped table-bordered text-center" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class='text-center'>Incidente</th>
                            <th class='text-center'>Criado em</th>
                            <th class='text-center'>Detalhe</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php
                            $i=0;
                            if (isset($dados_table_aberto)) {
                                foreach ($dados_table_aberto as $th) {
                                    echo "<tr>
                                                <th class='text-center'>$th[0]</th>
                                                <th class='text-center'>$th[3]</th>
                                                <th class='text-center'><button id='buttonDetalheModal$i' class='btn btn-primary' name='buttonDetalheModal$i'><i class='fa fa-folder-open-o' aria-hidden='true'></i> Laudo</button></th>
                                            </tr>";
                                    $i++;
                                }
                            }
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="card-footer text-muted">
                Dados do Usuário
            </div>
        </div>


        <div id="cardGrafico" class="card text-center col-6 text-white bg-dark container">
            <div class="card-header">
                <p class="font-weight-bold"><i class="fa fa-area-chart" aria-hidden="true"></i> GRÁFICO</p>            </div>
            <div class="card-body">
                <div id="graficoIncidente" style="margin: 0 auto"></div>
            </div>
            <div class="card-footer text-muted">
                Dados do Usuário
            </div>
        </div>

        <?php
        for ($i=0; $i <count($UserQTD); $i++) {
            echo "<input id='hiddenDado$i' class='dadosGrafico' type='hidden' name='hiddenDado$i' value='$UserQTD[$i]'>\n";
        }
        ?>
    </div>
</section>