<div class="container">
    <h2>Novo Post</h2>

    <?php if(isset($error)): ?>
    <div class="alert alert-danger"><?= $error ?></div>
    <?php endif; ?>
    
    <div class="row">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    Formuláriode cadastro de post
                </div>
                <div class="card-body">
                    <form action="<?= PATH ?>/admin/posts/add" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="titulo">Título</label>
                            <input type="text" class="form-control" id="titulo" name="titulo" placeholder="título">
                        </div>
                        <div class="form-group">
                            <label for="titulo">Descrição</label>
                            <textarea name="descricao" class="form-control" id="descricao" rows="10" cols="30" placeholder="descrição"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>