<div class="container">
    <h2>Editar Post</h2>

    <?php if(isset($error)): ?>
        <div class="alert alert-danger"><?= $error ?></div>
    <?php endif; ?>

    <div class="row">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    Formuláriode de edição de post
                </div>
                <div class="card-body">
                    <form action="<?= PATH ?>/admin/posts/<?= $post->ID_HISTORICO ?>/edit" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="titulo">Título</label>
                            <input type="text" class="form-control" id="titulo" name="titulo" placeholder="título" value="<?= $post->NOTA ?>">
                        </div>
                        <div class="form-group">
                            <label for="titulo">Descrição</label>
                            <textarea name="descricao" class="form-control" id="descricao" rows="10" cols="30" placeholder="descrição"><?= $post->NOTA ?></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Atualizar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>